import Head from "next/head";
import {
  VStack,
  Center,
  Text,
  Heading,
  AbsoluteCenter,
  Button,
  Input,
  FormControl,
  Select,
  Box,
  Container,
} from "@chakra-ui/react";
import { useState } from "react";
import axios from "axios";

export default function Home() {
  const [isLoading, setIsLoading] = useState(false);
  const [learn, setLearn] = useState("");
  const [filter, setFilter] = useState("AI");
  const [data, setData] = useState("");

  const handleInputFormChange = (event: any) => {
    setLearn(event.target.value);
  };

  const handleDropDownChange = (event: any) => {
    setFilter(event.target.value);
  };

  const gptPostClient = axios.create({
    baseURL: "https://api.openai.com/v1/completions",
  });

  const returnResults = async () => {
    setIsLoading(true);
    const prompt =
      "You will become the most well published and well known expert" +
      filter +
      " professor at an Ivy League University. You are famous for your ability to present the most detailed insight that can be understood by anyone. I am a student coming to you for help. Please create a comprehensive, detailed, organized list so I can teach myself" +
      learn +
      ".Please include detailed examples and step-by-step lists to demonstrate concepts when starting the response say Here is your roadmap made by MapAI";

    gptPostClient
      .post(
        "",
        {
          model: "text-davinci-003",
          prompt: prompt,
          max_tokens: 1000,
          temperature: 0,
        },
        {
          headers: {
            "Content-Type": "application/json",
            Authorization:
              "Bearer " + "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",
          },
        }
      )
      .then((resp) => {
        console.log(resp.data.choices[0].text);
        setData(resp.data.choices[0].text);
      });
    setTimeout(() => {
      setIsLoading(false);
    }, 5000);
  };

  return (
    <>
      <Head>
        <title>MapAi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center>
        <VStack maxW="6xl" h="100vh" gap="50px">
          <Heading mt="10">Create your personal roadmap</Heading>
          <FormControl id="prompt" fontSize={"2xl"} pt="10">
            <Box>
              <Text>What space is your roadmap for?</Text>
              <Select
                placeholder="Tech"
                _placeholder={{ color: "gray.500" }}
                textAlign="match-parent"
                width={"50"}
                onChange={handleDropDownChange}
              >
                <option>AI</option>
                <option>Engineering</option>
                <option>Wellness</option>
                <option>Exercise</option>
                <option>Religion</option>
              </Select>
            </Box>

            <Box mt="50">
              <Text>I want a roadmap to</Text>
              <Input
                placeholder="help me learn..."
                size="lg"
                onChange={handleInputFormChange}
                value={learn}
                id="learn"
                name="learn"
              />
            </Box>
          </FormControl>
          <Button
            bg="#4FAD27"
            color="white"
            size="lg"
            h="20px"
            onClick={returnResults}
            isLoading={isLoading}
          >
            {" "}
            Create a Roadmap
          </Button>
          <Box padding="6" bg="white" borderRadius="lg">
            <Text>{data}</Text>
          </Box>
        </VStack>
      </Center>
    </>
  );
}
